### ISSUE TITLE
TNB Heroes - Specification - 1

### ISSUE THREAD

**Issue by Kycermann** [thenewboston-developers/Projects#220]
#### Link to the milestone and objectives table.
https://github.com/thenewboston-developers/Projects/issues/217

#### Detailed log of all completed objectives including valid proof of work.
 https://docs.google.com/document/d/1Xk3pjTeaT0KHkCrc6znfOrbSvu44aSI3Oa-U94wCL84/edit?usp=sharing

#### Project Wallet
f1decb80339a4bb6c089b77cbac553e23a6ca86b0cfc64adb8c8eb8f8b57d815

**Comment by angle943** [comment]
Approved for 6,000 tnbc coins.

For the next milestone, however, could you make a  UI wireframe/flowchart of how the game will look like? IE how the home screen with all your items will look like, how battles will look like, trade screen, etc. (basically all screens you may potentially see in the game.) This will help us understand what type of game this is. (ex: https://dribbble.com/shots/2638922-Mobile-UI-Set-Wireframe-WIP/attachments/528621)

We are asking because we still aren't sure whether the battle portions will be like Pokemon, or Diablo, or a random win/loss situation, etc.

We (the auditors & govt) are still having a hard time grasping how everything will look like & play like, so we fill that some visual guides will help us better assess what is going on.

We will give you 3,000 upon the completion of this.

**Comment by Kycermann** [comment]
> Approved for 6,000 tnbc coins.
> 
> For the next milestone, however, could you make a UI wireframe/flowchart of how the game will look like? IE how the home screen with all your items will look like, how battles will look like, trade screen, etc. (basically all screens you may potentially see in the game.) This will help us understand what type of game this is. (ex: https://dribbble.com/shots/2638922-Mobile-UI-Set-Wireframe-WIP/attachments/528621)
> 
> We are asking because we still aren't sure whether the battle portions will be like Pokemon, or Diablo, or a random win/loss situation, etc.
> 
> We (the auditors & govt) are still having a hard time grasping how everything will look like & play like, so we feel that some visual guides will help us better assess what is going on.
> 
> We will give you 3,000 upon the completion of this.

Hey Justin, thank you for looking at my project (TNB Heroes). I'm not sure that it's the right time for a wireframe but I understand that it's hard to make sense of my specs- and that's on on me!

Battles will always be deterministic and have an instant outcome- to prevent botting. I kept the spec simple on purpose to make an MVP- and the only determining factors in the MVP are Health Points and Fight Power. Later on we'll have skills, companions and lots of interesting things that make battles interesting.

Battles will work like this:
1. Two players can battle
2. The battle has rounds
3. Each round, each player damages the other by their Fight Power, taking away from the other player's Health Points
4. The first player to reach 0 Health Points loses the battle

Tournaments will initially work like this:
1. Every player battles every other player
2. Players get 1 point per win
3. Points are divided by number of participants to calculate a percentage
4. Winners are sorted by percentages of wins
5. Different prizes are given to the top 1, 2, 3, 10 and 100 players (managed by Game Masters)

I'm not sure that it's the right time for a wireframe because the first milestone is all about the backend and mechanics. Primarily this is a collectible game, and all aspects of it will always be deterministic.

**Comment by buckyroberts** [comment]
@Kycermann thanks for the quick response. We now have a much better understanding on how this game will work. Feel free to submit your next [Milestone Proposal](https://github.com/thenewboston-developers/Projects/issues/new?assignees=&labels=Milestone&template=milestone-proposal.md&title=NAME_OF_PROJECT+-+NAME_OF_MILESTONE+-+MILESTONE_NUMBER)!
