### ISSUE TITLE
TNB-DISCORD BOT - Whole bot - 1

### ISSUE THREAD

**Issue by mrbusysky** [thenewboston-developers/Projects#256]
#### Link to original project proposal.
https://github.com/thenewboston-developers/Projects/issues/143

#### Link to most recent milestone payout request.
N/A

#### Repo
https://github.com/Keysign-Wallet/TNB-BOT

#### Milestone Description
Completed the whole discord bot.

| # | Objective             | How can auditors verify milestones?     |
| - | --------------------- | -------------------------------------- |
| 1 | Whole bot is completed | you can check repo and test bot live|

#### How long do you estimate this milestone will take to complete?
Already completed

#### Project Wallet
32d8b9aeb1646c9e17d90b36451ce5b853b6e72cbeaf65ad8d7687137b683ee6

**Comment by tspearing** [comment]
Hi @mrbusysky, we've reviewed this and propose 40k TNBC for this milestone and agree the milestone is complete. Please create a milestone payment request.

**Comment by mrbusysky** [comment]
I'm sorry but we can take no less than 84k

https://docs.google.com/document/d/1NYFMZuqcubAGCYPB7bBYUC6rCjyqRP9kh5XOp6IJ6q0/edit

This project is the only thing really keeping people active in the discord community besides projects,
The rain feature/giveaway feature and keeping people coming back.

We also plan to keep adding more features without funding from the community going forward.
Also we provide things like an api for the community to utilize and build on.

We should be asking for more than what we are asking for. I even waved my payment in the project.

**Comment by tspearing** [comment]
@mrbusysky, a few thoughts:
1) This project was paid previously when projects were paid 2800 per person per day. We calculate that 39200 TNBC has already been paid.https://github.com/thenewboston-developers/Contributor-Payments/issues/98
2) In the google doc linked (https://docs.google.com/document/d/1NYFMZuqcubAGCYPB7bBYUC6rCjyqRP9kh5XOp6IJ6q0/edit) the hours for FilterUnfiltered do not add up to 32:23. The time is 19:30.
3) Projects are not paid based on an hourly rate, but based on network value. We agree that the project is worth around 80k TNBC which is why we proposed 40k TNBC.
4) If there will be future upgrades, please submit a milestone request and we will gladly review them.

**Comment by FilterUnfiltered** [comment]
Actually, after doing it again quickly it turns out to be exactly 23:33 for my part, so clearly that was a small miscalculation on both of our parts. 

You say the value is based on network value. I can guarantee that the rains and giveaways from the bot have been the sole reason for many people to be sticking around. That means it is essentially one of the major contributors keeping it from dying out early. Since you said it isn't hourly then we can remove our reasoning for 84k, and simply ask for 84k for the value it provides. Also, we won't be doing more milestones since doing all this has already proven to be a hassle, and we will be operating on our own from now on since there are other ways to earn coins from the bot, which we have intentionally not added since we expected we will be getting paid anyway. 

On the discord server, the person with the absolute most activity is MrSky (Checked by using Mee6 bot, which keeps track of activity), starting November 18, 2020. He has a total of 307 pages of messages when searching the server history, starting. The bot, which has only been around since March 21 of this year, has 186 pages. The bot has been around for less than half the time and has a lot more than half the activity, making it the absolute most active "member" on the discord. (Quick note: this includes a large period of time when the bot only let you register to display an address and that's it. This was when nobody used it AT ALL, and usage only started ramping up when rains got added in EARLY APRIL, meaning the bot has really only had 3 months to gain up compared to MrSky's 8+)

The price we are asking for is what we are hoping will pay not only for what we have done but also what we will continue to do as the bot evolves to allow things such as marketplaces, reward systems, and more, right on discord. This is something I know has been asked for to reward the meme contest winners on the discord more easily. 

One final note is this: If you were to actually take a look at the github page you would notice that a lot of things have been redone multiple times at the request of the main team, and these have not been included in the document. We feel like the value asked is more than fair taking all of this into account, especially considering the bot is probably doing more for the health and growth of the community than your marketing team, which I can guarantee is getting paid a lot more than us.

**Comment by buckyroberts** [comment]
Hey @FilterUnfiltered. The government and audit team met last week to discuss this issue. After discussing both the benefits of the bot and the value it has provided to the community, each of us independently gave our own valuation of the project as a whole. After averaging each of our valuations we arrived at ~80K. We then discussed each of our valuations to understand each other's specific reasoning, and afterwards agreed that ~80K was a fair valuation. We then checked the project's payout history and saw that 39,200 coins have already been paid out. The remaining amount which represented the value that was not yet paid was how we arrived at 40K (we will bump that to 40,800 since it's more accurate). For any additional improvements or features added in the future, those will be developed under additional milestones which would be given valuations and paid out separately from this one.

**Comment by mrbusysky** [comment]
> 
> 
> Hey @FilterUnfiltered. The government and audit team met last week to discuss this issue. After discussing both the benefits of the bot and the value it has provided to the community, each of us independently gave our own valuation of the project as a whole. After averaging each of our valuations we arrived at ~80K. We then discussed each of our valuations to understand each other's specific reasoning, and afterwards agreed that ~80K was a fair valuation. We then checked the project's payout history and saw that 39,200 coins have already been paid out. The remaining amount which represented the value that was not yet paid was how we arrived at 40K (we will bump that to 40,800 since it's more accurate). For any additional improvements or features added in the future, those will be developed under additional milestones which would be given valuations and paid out separately from this one.

Okay, we will take it but moving forward will be maintaining and devloping everything on our own.
