### ISSUE TITLE
TNBPAY - MILESTONE 2 & 3

### ISSUE THREAD

**Issue by olowudaniel1** [thenewboston-developers/Projects#263]
#### Link to the milestone and objectives table.
#225 

#### Detailed log of all completed objectives including valid proof of work.
The Wordpress plugin has  been developed, tested and ready for use.

Github repo: https://github.com/akandejaphet/TNBPay
Documentation: https://github.com/akandejaphet/TNBPay/blob/master/Documentation/TNBPAY%20Documentation.pdf
Demo: https://github.com/akandejaphet/TNBPay/blob/master/Documentation/demo.gif

#### Project Wallet
86ee75d4cea77ca8339cc97f5e7426a3434d9f91465cd441c0c7593bd852e955

**Comment by tspearing** [comment]
@olowudaniel1, this is looking like there's been a lot of progress!

The main issue we're having is getting a transaction to go through. Both Manish and I tried but it stalled after we pressed "Payment made, next".
![image](https://user-images.githubusercontent.com/77364430/125718250-1aeb0bdd-9c24-4bb5-8bb2-48e76e899210.png)



A couple of other requests:
1) For the currency, change Tnbc (TNB) to TNBC (TNBC)
2) Add a copy button in the check out and display the whole account number
3) Add a copy button to the memo

**Comment by tspearing** [comment]
Are there any solutions if someone over pays?

Or if someone under pays, can they send the balance with the same memo to fix it?

Here's a document where we discussed some of these thoughts:
https://docs.google.com/document/d/1am0X2XrlcsPEtb997lNLhTFfRQp7mRiND9QJ8uWoG6A/edit

**Comment by olowudaniel1** [comment]
Hello

All 3 fixes has been made. The error you got after making payment was probably as a result of theme conflict and that has been fixed also.

![TNBPAY -updated clipboard](https://user-images.githubusercontent.com/79472442/126039935-a7b541d6-3a33-4f7e-a831-ab17454b2820.JPG)

We also have resolved the issue of OVERPAYMENT and UNDERPAYMENT.

for UNDERPAY

The Buyer gets an alert that he underpaid after that the modal and the timer reloads showing him the outstanding amount he should pay.  The store owner is also alerted that the  buyer underpaid under the order notes. The order notes would include the MEMO, amount the buyer paid, amount left, Account number of the buyer.

![UNDERPAID TNB](https://user-images.githubusercontent.com/79472442/126039964-c559f3dd-fab6-4f73-af19-935ed79c8336.JPG)

![underpay1](https://user-images.githubusercontent.com/79472442/126040037-df18e2ae-b60b-4ce3-87a4-a6af9575ec7a.JPG)

for OVERPAY

The Buyer gets an alert that he overpaid and he should contact the store owner or wait for a refund, after that the order is completed.  The store owner is also alerted that the  buyer overpaid under the order notes. The order notes would include the MEMO, amount the buyer paid, amount to refund, Account number of the buyer.

![TNB OVERPAID](https://user-images.githubusercontent.com/79472442/126039986-5e305eb8-2ecf-4fcb-bcb4-4a354afca6a5.JPG)

![tnb overpaid store](https://user-images.githubusercontent.com/79472442/126040016-263ba77f-a53a-45a8-966b-8c80c66b4d82.JPG)



for Wrong Memo

This would rarely happen the event of this  happening, the Buyer would have to contact the store owner.


However, all these  wouldn't be an issue once QR scan and Quick Pay are available.

The Docs would be updated also

**Comment by tspearing** [comment]
Hi @olowudaniel1, thanks for adding the copy buttons to the account number and the memo. Would it be possible to make the whole account number visible?

We attempted to test the overpayment but got the same 500 error. Next, we tried the correct payment but it was the same.

The wordpress installation is fresh and I re-downloaded the zip file to install the plugin.

We'd like to invite you to a meeting to try to sort this out. Are you available at 7PM PST?

**Comment by olowudaniel1** [comment]
All Issues fixed.

**Comment by tspearing** [comment]
@olowudaniel1, this looks really good!

We approve this milestone. Below are a few changes we'd like to request. These are slight changes, sometimes for legal reasons. For example with #1, we don't want to promise that the store owner will pay back because they might be dishonest. 

1) Please change "You over paid the store owner will refund you or reach out to them" to "You over paid. Please reach out to the store owner to discuss the return of the extra coins".

2) Please change "User Overpaid: Please refund the user and amount of TNBC[overpayment amount] to this account number [account number]" to "User Overpaid [overpayment amount] TNBC. Please discuss the overpayment with the customer or refund them at [account number].

3) When there's an underpayment, could you state what the new balance is? It would be good to have the new balance here, but it disappears:
![image](https://user-images.githubusercontent.com/77364430/126420234-624175ce-8e9c-4e43-b83d-21200964abdd.png)

Could this show the original balance and also show the new amount owed in order to meet the proper amount?
![image](https://user-images.githubusercontent.com/77364430/126420381-e925be32-c9ad-4251-b908-ffdab04fb9a5.png)

**Comment by olowudaniel1** [comment]
Thanks for the feedback. I would create this as an issue and it would be implemented in the next release ASAP

**Comment by jamessspanggg** [comment]
Just a question, I'm curious as to how does one overpay or underpay? is it during or before the transaction, the price of TNB changes?

**Comment by olowudaniel1** [comment]
@jamessspanggg  this happens when the user input the wrong amount in the account manager at the point of payment
