### ISSUE TITLE
suppCoins - back-end ORM - 1.2 [REQUESTED]

### ISSUE THREAD

**Issue by Toledit** [thenewboston-developers/Projects#273]
#### Link to the milestone and objectives table.
#193

#### Detailed log of all completed objectives including valid proof of work.
As requested by the audit team, We have included down below the ORM diagram for our app. 
Feel free to comment down below for clarifications if any.

**_back-end ORM_**
https://github.com/suppCoins/Design/issues/2#issuecomment-894514882

we are not yet submitting _backend milestone_ but you can check out backend progress on suppCoins GitHub page
https://github.com/suppCoins/Back-End/tree/master
 
#### Project Wallet
449baf4c0b43f44e9b091947bf36880bf237a91e413adb85ca2ae1f33e239440

**Comment by hussu010** [comment]
Hi, (not from the core team) but still had some questions regarding the application flow.

- Will the donator need to create an account to donate TNBC through suppCoins?
- What does the content in the ORM mean? Is it the platform or the actual content inside the platform?
- Could a single user be a creator and a donator or do they need to register themselves in two places? (I suggest using the same profile model for the creator and donator)

Also, a suggestion for the Django Backend, could the GenericAPIViews be used instead of APIViews since they make the task a lot easier without the need to write extra code.

Let me know if the team requires someone to write the backend tickets and check the PRs as we also need to ensure the quality of the code alongside the delivery of the application.

Cheers!!

**Comment by Toledit** [comment]
Hi Hussu, 
1. yes, The donator needs to create an account to donate to stand out or stay anonymous if need be.
2. content represents: in case of the youtube platform, a video or on Github, specific opensource project ...
3. yes, Creator can be a donator. And no they do not use the same model. just because the donator needs to fill out a minimum amount of info to make it simpler. 

Thanks! I have transferred your suggestion to our backend guy.

**Comment by manishram** [comment]
Paid 5000 TNBC for this milestone.
